### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by lucarin91** [di-unipi-socc/TosKeriser#5]
This `node_filter` should be not valid, instead pass validation:
```
node_filter:
  properties:
  - ports: {8080: 8080}
  - supported_sw:
    - java: 1.8.x
    - mvn: 3.5.x
  - os_distribution: debian
  ```
